[2025-02-02 18:06:08,469 ] 14 root ERROR Error occurred in python script name [/home/mayur/Network Security/push_data.py] at line number [37] error message ['str' object has no attribute 'values']
